
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kuupszdkcowmyjycnkgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1dXBzemRrY293bXlqeWNua2doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NDYyMjEsImV4cCI6MjA2MzQyMjIyMX0.WPqdaaeXubwtP_vu0YjvXQkV9xY5Gnm5JLXu-a6olj4";

// Create an augmented type that extends the Database type to include our custom functions
type AugmentedSupabaseClient = ReturnType<typeof createClient<Database>> & {
  // Add a type-safe overload for our custom RPC functions
  rpc<T = any, R = any>(
    fn: string,
    params?: T
  ): Promise<{ data: R; error: null } | { data: null; error: any }>;
};

// Export the client with proper configuration for auth
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage
  }
}) as AugmentedSupabaseClient;
