// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kuupszdkcowmyjycnkgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1dXBzemRrY293bXlqeWNua2doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NDYyMjEsImV4cCI6MjA2MzQyMjIyMX0.WPqdaaeXubwtP_vu0YjvXQkV9xY5Gnm5JLXu-a6olj4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);